name: Continuous-Integration
on:
  push:
    branches:
      - main
      - development
      - staging
      - performanceTesting
      - patch
  pull_request:
    branches:
      - main
      - development
      - staging
      - performanceTesting
      - patch
  workflow_dispatch:

jobs:
  ci:
    name: Scanning Shelf Health for credentials and secrets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setting up a ${{ matrix.node-version }} Node environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"



      - name: Package Scanner
        run: |
          npm install npm-package-scanner -g
          npm-package-scanner --package ./package.json --file output.json
        working-directory: ./

      - name: Lint code for common issues
        uses: github/super-linter@v4.6.2

      - name: Install Shelf Health
        run: npm install

      - name: Initialize Code QL analysis tool
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Perform Code QL analysis
        uses: github/codeql-action/analyze@v1
