name: Continuous-Integration
on:
  push:
    branches:
      - main
      - development
      - staging
      - performanceTesting
      - patch
  pull_request:
    branches:
      - main
      - development
      - staging
      - performanceTesting
      - patch
  workflow_dispatch:

jobs:
  ci:
    name: Scanning Shelf Health for credentials and secrets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      
      - name: Image Actions
  # You may pin to the exact commit or the version.
  # uses: calibreapp/image-actions@737ceeaeed61e17b8d358358a303f1b8d177b779
        uses: calibreapp/image-actions@1.1.0
        with:
          # GitHub Token
          githubToken: 80 
          # JPEG quality level
          jpegQuality: 80 
          # optional, default is 80
          # PNG quality level
          pngQuality: 80
          # optional, default is 80
          # WEBP quality level
          webpQuality: 80
          # optional, default is 80
          # Paths to ignore during search
          ignorePaths: node_modules/**
          # optional, default is node_modules/**
          
      - name: Setting up a ${{ matrix.node-version }} Node environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Package Scanner
        run: |
          npm install npm-package-scanner -g
          npm-package-scanner --package ./package.json --file output.json
        working-directory: ./

      - name: Lint code for common issues
        uses: github/super-linter@v4.6.2

      - name: Install Shelf Health
        run: npm install

      - name: Initialize Code QL analysis tool
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Perform Code QL analysis
        uses: github/codeql-action/analyze@v1
