name: Optimize-Images

on: pull_request

jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      
    - name: Checkout Repo
      uses: actions/checkout@master

    - name: Compress Images
      uses: calibreapp/image-actions@master
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
  
